sudo: required
dist: trusty

install:
# Install docker according to official docker docs.
 - sudo apt-get update

 - sudo apt-get install -y linux-image-extra-$(uname -r) linux-image-extra-virtual

 - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

 - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

 - sudo apt-get update

 - sudo apt-get -y install docker-ce

 - sudo curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose

 - sudo chmod +x /usr/local/bin/docker-compose

before_script:
  - docker-compose up

script:
 - python tests/functional_tests.py

after_script:
 - docker-compose down


