sudo: required
dist: trusty

install:
# Install docker according to official docker docs.
 - apt-get update

 - apt-get install -y linux-image-extra-$(uname -r) linux-image-extra-virtual

 - apt-get -y install \
    apt-transport-https \
    ca-certificates \
    curl \
    software-properties-common

 - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

 - add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"

 - apt-get update

 - apt-get -y install docker-ce

 - curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose

 - chmod +x /usr/local/bin/docker-compose

before_script:
  - docker-compose up

script:
 - python tests/functional_tests.py

after_script:
 - docker-compose down


