sudo: required
dist: trusty

addons:
  firefox: "latest-nightly"

install:
# Install docker according to official docker docs.
 - pwd
 
 - ls
 
 - sudo apt-get update

 - sudo apt-get install -y linux-image-extra-$(uname -r) linux-image-extra-virtual

 - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

 - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

 - sudo apt-get update

 - sudo apt-get -y install docker-ce

 - sudo curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > docker-compose

 - sudo chmod +x docker-compose
 
 - sudo mv docker-compose /usr/local/bin
 
 - wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
 
 - sudo cp geckodriver-v0.11.1-linux64.tar.gz /usr/local/bin
    
 - cd /usr/local/bin && sudo tar xzf geckodriver-v0.11.1-linux64.tar.gz
 
 - pip3 install selenium
    
 - echo $PATH

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo sysctl -w vm.max_map_count=262144
  - cd /home/travis/build/b00kwrm/jug-of-test
  - docker-compose up -d

script:
 - python3 tests/functional_tests.py

after_script:
 - docker-compose down


